#!/bin/bash

# Jagechas Quick Commands Reference
# Run these commands from the Jagechas root directory

echo "🔍 JAGECHAS - Quick Commands Reference"
echo "======================================="
echo ""

echo "📦 INSTALLATION COMMANDS:"
echo "-------------------------"
echo "Install all dependencies:"
echo "  npm install && cd server && npm install && cd ../client && npm install && cd .."
echo ""

echo "🗄️ DATABASE SETUP:"
echo "------------------"
echo "Seed the database (run from server directory):"
echo "  cd server && node seed.js"
echo ""

echo "🚀 START DEVELOPMENT:"
echo "---------------------"
echo "Start both frontend and backend (from root):"
echo "  npm run dev"
echo ""
echo "OR start separately:"
echo "  Terminal 1: cd server && npm run dev"
echo "  Terminal 2: cd client && npm start"
echo ""

echo "🧪 TESTING CREDENTIALS:"
echo "------------------------"
echo "Admin:"
echo "  admin@jagechas.com / password123"
echo ""
echo "Companies:"
echo "  company@hul.com / password123"
echo "  company@dabur.com / password123"
echo "  company@itc.com / password123"
echo ""
echo "Users:"
echo "  rahul@example.com / password123"
echo "  priya@example.com / password123"
echo "  amit@example.com / password123"
echo ""

echo "🌐 ACCESS URLS:"
echo "---------------"
echo "Frontend: http://localhost:3000"
echo "Backend:  http://localhost:5000"
echo "API:      http://localhost:5000/api"
echo ""

echo "📚 DOCUMENTATION:"
echo "-----------------"
echo "Setup Guide:      SETUP.md"
echo "MongoDB Setup:    MONGODB_SETUP.md"
echo "Completion Check: CHECKLIST.md"
echo "Main README:      README.md"
echo ""

echo "🛠️ TROUBLESHOOTING:"
echo "--------------------"
echo "MongoDB not running?"
echo "  macOS: brew services start mongodb-community"
echo ""
echo "Port already in use?"
echo "  Kill port 5000: lsof -ti:5000 | xargs kill -9"
echo "  Kill port 3000: lsof -ti:3000 | xargs kill -9"
echo ""
echo "Dependencies issues?"
echo "  Clean install: rm -rf node_modules && npm install"
echo ""

echo "✅ Ready to start! Run: npm run dev"
echo ""
